runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
network:
  forwarded_ports:
    - 8080
health_check:
  enable_health_check: false
service: leap
runtime_config:
  build:
    image: us-east1-docker.pkg.dev/dulcet-voyager-351710/dock/dock:latest
