steps: 
- name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the secret and store it in a file
        gcloud secrets versions access latest --secret="test" > secret_file.txt
        echo secret_file.txt
