steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'rm', '-r', './', 'gs://${_GCS_BUCKET}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', './', 'gs://${_GCS_BUCKET}']
